name: Build & Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write
  id-token: write

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload wheel to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        environment: pypi

  build-win-exe:
    runs-on: windows-latest
    needs: build-whee
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Build EXE with PyInstaller
      - name: Build EXE
        run: pyinstaller --noconsole --onefile --name DeeFuse --icon assets/deefuse_desktop.ico src/deefuse/__main__.py


      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DeeFuse.exe
