name: Build & Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build --wheel
      - name: Upload wheel to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl

  build-win-exe:
    runs-on: windows-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v4
      - name: Build EXE with PyInstaller
        run: |
          python -m pip install --upgrade pip pyinstaller
          pyinstaller --noconsole --onefile -n DeemixHybridGUI src/deemix_gui/__main__.py
      - name: Upload EXE to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DeemixHybridGUI.exe
