build-win-exe:
  runs-on: windows-latest
  needs: build-wheel

  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build deps
      run: |
        python -m pip install --upgrade pip
        pip install .[dev] pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconsole --onefile `
                    --name DeeFuse `
                    --icon assets/deefuse_desktop.ico `
                    src/deefuse/__main__.py

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/DeeFuse.exe
