name: Build & Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload wheel to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl

  build-win-exe:
    runs-on: windows-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconsole --onefile -n DeeFuse run_deefuse.py

      - name: Upload EXE to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DeeFuse.exe
